require("Libs/Library")
local multi = require("multi")
local bin = require("bin")
GLOBAL,sThread = require("multi.integration.loveManager").init()
require("GuiManager")
require("parseManager")
function love.update()
	multi:uManager()
end
multi.OnError(function(...)
	print(...)
end)
VNCore = require("VNCore").init(gui:newFullFrame("Main"), parseManager, multi)
